### ISSUE TITLE
Writes plain-text log files

### ISSUE THREAD

**Issue by derobert** [reyk/systemd-openbsd#3]
It sounds like /var/log/authlog is an ordinary, plain-text log file, the type of thing a desperate sysadmin could read with no special tools and might expect to even survive a system crash. I feel that you've missed a [vital systemd feature](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html) there.

:smiling_imp:

**Comment by reyk** [comment]
You are right! See the referenced pull request and branch. This is all I can do at the moment.

**Comment by reyk** [comment]
merged
